### ISSUE TITLE
[Bug] fix renamed_relations for 1.8

### ISSUE THREAD

**Issue by VersusFacit** [dbt-labs/dbt-adapters#108]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

See [this core ticket](https://github.com/dbt-labs/dbt-core/pull/9682) for more.

### Expected Behavior

See linked ticket

### Steps To Reproduce

See linked ticket

### Environment

```markdown
See linked ticket
```

**Comment by Fleid** [comment]
Hey @VersusFacit, moving this to `unestimated`, but should it be `in progress` in a sprint?

**Comment by martynydbt** [comment]
@VersusFacit the linked core issue is a pull request. Did you mean to link an issue?

**Comment by mikealfare** [comment]
There is no backport for this because 1.7 was part of dbt-core. This will be handled in https://github.com/dbt-labs/dbt-core/issues/9681
