### ISSUE TITLE
[Bug] Update CONTRIBUTING.md to Reflect Current Functional Testing Process

### ISSUE THREAD

**Issue by pavelerokhin** [dbt-labs/dbt-adapters#114]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The functional testing section in the CONTRIBUTING.md file of the dbt-adaptors repository is outdated and irrelevant to the current scope of the repository. It primarily focuses on functional testing procedures that are no longer applicable.

### Expected Behavior

To update the CONTRIBUTING.md file to reflect the appropriate methods for performing functional testing with both dbt-core and dbt-adapters repositories.

### Steps To Reproduce

In the `CONTRIBUTING.md` file go to the section Functional tests

### Environment

```markdown
- OS:Ventura 13.2.1
- Python:3.9.6
- dbt-adapter:
```

**Comment by Fleid** [comment]
@colin-rogers-dbt @mikealfare there may already be a ticket somewhere about that?
