### ISSUE TITLE
[Feature] warn users that `dbt-core~=1.8.0` needs to be explicitly installed

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-adapters#139]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-adapter functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I propose we add a generic warning to dbt-adapter's `setup.py` that says something like the below

> As of dbt-core>=1.8, users must install both an adapter and dbt core, ie
> `pip install dbt-ADAPTER dbt-core`
> For more information, see https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.8#new-dbt-core-adapter-installation-procedure

Copilot suggested to me the below addition to `setup.py`. 

```py
import warnings

warnings.warn("""
As of dbt-core>=1.8, users must install both an adapter and dbt core, ie
`pip install dbt-ADAPTER dbt-core`
For more information, see https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.8#new-dbt-core-adapter-installation-procedure
""")
```

However, given `setup.py` is being "deprecated" in favor of `pyproject.toml`, this is a stop-gap solution. IMHO, this is fine as the warning exists solely to guide users upgrading from versions less than 1.8 to versions greater than or equal to 1.8

**Comment by amychen1776** [comment]
I would love to tackle this but due to capacity, we will not be able to pick this up. Appreciate you through!
