### ISSUE TITLE
[Feature] `pre-commit` install and usage instructions within contributing guide

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-adapters#180]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-adapter functionality, rather than a Big Idea better suited to a discussion

### Request

Add instructions for the following:
1. Installing pre-commit
1. Running all pre-commit hooks (or a single hook)

### More detail
Include instructions for installing `pre-commit` within `CONTRIBUTING.md` similar to dbt-core [here](https://github.com/dbt-labs/dbt-core/blob/8736508617eb45f811c9246e00dcd79b67fb12b5/CONTRIBUTING.md#installation) and dbt-common [here](https://github.com/dbt-labs/dbt-common/blob/b76d0e655a81873646f9d32a9e4df170cedcafa8/CONTRIBUTING.md#initial-setup).

Namely:
```
pre-commit install
```

Alternatively, provide instructions for running the relevant hatch script.

Then also provide instructions for running all hooks:

```shell
pre-commit run --all-files
```

or:

```shell
pre-commit run --all-files --show-diff-on-failure
```

And also instructions for running a single hook (where `HOOK_ID` is a hook ID within `.pre-commit-config.yaml`):
```shell
pre-commit run HOOK_ID --hook-stage manual
```

### Who will this benefit?

Contributors

**Comment by mikealfare** [comment]
These are effectively aliases, but `hatch run dev` will run `pre-commit install` and build the default environment (think `make dev`). And `hatch run code-quality` will run `pre-commit run --all-files`. I have not setup `hatch run code-quality` to take additional arguments, though we probably should. And there is no longer a difference in stage, so you don't need that argument.

Something else worth noting, we do eventually want to move all adapters over to `hatch`, but we have not done that yet. So we're in the grey area where there is a different way for different repos. I'm not sure on the timing on this, but we probably want to do this along with the work of migrating to `hatch`, and store the "how to" somewhere common, like dbt-labs/oss-at-dbt.

**Comment by dbeatty10** [comment]
That is great info @mikealfare 💡

I'd advocate for keeping each of the individual contributing guides fully up-to-date with relevant instructions. That way adapters that are using hatch have specific instructions and those that don't also have instructions that work.

I'd be glad to help close any gaps in the meantime until we have a place to store a common "how to".
