### ISSUE TITLE
Change the default behavior of `get_show_sql` to avoid wrapping in subquery

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-adapters#207]
**Context:**
- https://github.com/dbt-labs/dbt-core/issues/9600
- [internal slack thread](https://dbt-labs.slack.com/archives/C03SK9W08BC/p1713265789155649)

**Implementation:**
- By default, `get_show_sql` should not wrap in a subquery. Instead, it should simply append `limit {{ limit }}` to the end of the query.
- This does not work for queries that already contain a `limit` clause, but it preserves ordering in all other cases.
- Because this only changes the behavior for `dbt show`, which is a development (not production) workflow, I do not believe this needs to be gated behind a behavior change flag. Users can always opt back into the previous behavior by reimplementing `get_show_sql` within their projects.

```sql
{% macro get_show_sql(compiled_code, sql_header, limit) -%}
  {%- if sql_header -%}
  {{ sql_header }}
  {%- endif -%}
  {{ compiled_code }}
  {% if limit is not none %}
  limit {{ limit }}
  {%- endif -%}
{% endmacro %}
```

**Acceptance tests:**
- I expect all existing tests to pass, since [`BaseShowLimit.test_limit`](https://github.com/dbt-labs/dbt-adapters/blob/d831caa33bc1a31d1162f1d1b3ccd6caaec08fd5/dbt-tests-adapter/dbt/tests/adapter/dbt_show/test_dbt_show.py#L28) is validating only that the `limit` is templated into the query (important!)
- Ideally, we'd write a new test that reliably reproduces incorrect ordering when the query is wrapped in a subquery, and then prove that it is always correctly sorted. Unfortunately I haven't managed to come up with a simple reproduction case of this.

**Comment by jtcohen6** [comment]
From estimation:
- existing macro, same signature
- not reimplemented in most adapters
- could add a test for the known failure mode (`limit` repeated twice: once within actual query, once by supplying `--limit` flag)

**Comment by VersusFacit** [comment]
See merge comments in #team-dev-adapters
