### ISSUE TITLE
[CT-1123] Adapter pre_model_hook + post_model_hook for tests and compilation, too

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-adapters#212]
Adapting from https://github.com/dbt-labs/dbt-snowflake/issues/23#issuecomment-1223773953:

Let's talk about `adapter.pre_model_hook` + `adapter.post_model_hook`.

### Background

Here's where they're triggered to run, right before and after a model materialization:

https://github.com/dbt-labs/dbt-core/blob/8c8be687019014ced9be37c084f944205fc916ab/core/dbt/task/run.py#L279-L283

These are _different_ from user-provided `pre-hook` and `post-hook`, which run _within_ materializations. (I wish we named these things a bit more distinctly). They are also no-ops by default:

https://github.com/dbt-labs/dbt-core/blob/8c8be687019014ced9be37c084f944205fc916ab/core/dbt/adapters/base/impl.py#L1093-L1116

For certain adapter plugins, these "internal" hooks are the appropriate mechanism for database-specific behavior that needs to wrap a node's execution. For instance, on `dbt-snowflake`, this is where we turn the `snowflake_warehouse` config into a `use warehouse` command. @dataders and I were just discussing the same principle for `use database` (compute _and_ storage) in serverless Azure Synapse (?).

### Current limitations
- These hooks are called for models, seeds, and snapshots, but not for tests, simply because the `TestRunner` does not inherit from the `ModelRunner` or extend its `execute` method (where `adapter.pre_model_hook` + `adapter.post_model_hook` get called). We've gotten the request to support `snowflake_warehouse` on tests several times.
- While these hooks appropriately wrap all queries called during materialization, they do _not_ seem to wrap compilation. Introspective queries called during compilation (e.g. `run_query`) will use the default warehouse (`target.warehouse` or user/role-configured), rather than the value of `snowflake_warehouse` configured on the model.

### Why improve this
- **Consistency.** This is what users expect to happen. Unified query history, so that all queries associated with a model actually use that model's configured compute.
- It's desirable to configure specific tests to run with beefier or lesser compute, just as with models.

**Comment by AlexanderStephenson** [comment]
We are using Snowflake, and for our environment the default warehouse is a small.  This is fast enough to run 95% of our models.  Where we have a a model where the number of rows pushes the limit of the warehouse we have used the config snowflake_warehouse with a macro get_warehouse to set a larger warehouse.  Using the macro we can set different warehouses for each of the different environments the model is being built in.  Dev, UAT, Production.

What we are experiencing now is the model is being successfully built with an XLarge warehouse, but the Tests are failing as these are defaulting back to the environments default warehouse which is a small.  The test is a unique test on a table with 14b rows.  So it is not complex SQL, just a lot of data.

**Comment by dbeatty10** [comment]
@AlexanderStephenson beginning in dbt-core v1.9 (currently in beta), you can do something like this to configure `snowflake_warehouse` for your models and data tests:

```yaml
models:
  - name: my_model
    config:
      snowflake_warehouse: something
    columns:
      - name: id
        tests:
          - accepted_values:
              values: [2]
              config:
                severity: warn
                snowflake_warehouse: something_else
```

Wanna give that a shot and see if it works for you?

**Comment by dbeatty10** [comment]
Closing as resolved by https://github.com/dbt-labs/dbt-core/pull/10767.

Please open an issue [here](https://github.com/dbt-labs/dbt-core/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=bug-report.yml&title=%5BBug%5D+%3Ctitle%3E) if you try this in dbt Core v1.9+ and it doesn't work for you.
