### ISSUE TITLE
[Bug] Clarification of implementing dbt-tests-adapter for adapters

### ISSUE THREAD

**Issue by cody-scott** [dbt-labs/dbt-adapters#283]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The current documentation around implementing the correct dbt-test-adapters is unclear.

The adapter creation guide mentions the dbt-tests-adapter (as part of this repo) https://docs.getdbt.com/guides/adapter-creation?step=4; there is also a dbt-tests-adapter package which looks to be maintained on pypi https://pypi.org/project/dbt-tests-adapter/ which might just be the built version of the link?

The cookiecutter also clones and references the tests adapter as part of the core project, not the adapters project, which pins the project to the latest main branch (1.9.0a1 at the current moment) which is problematic for developing against the stable version.

### Expected Behavior

Improved clarity around how adapter developers should be loading in the appropriate version for core/adapters in their projects. Perhaps a flag in the cookiecutter to also pin the development version to a specific version (`1.8.latest` for example).

Ideally for a developer if they can clone the pypi package and avoid the git+ clones it might be clearer.

### Steps To Reproduce

NA

### Environment

```markdown
- OS:
- Python:
- dbt-adapters:
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @cody-scott ! 🏆

You are correct that this repo has multiple packages that are released on PyPI. One of them is [`dbt-tests-adapter`](https://pypi.org/project/dbt-tests-adapter/), and its source code is rooted [here](https://github.com/dbt-labs/dbt-adapters/tree/f1987d4313cc94bac9906963dff1337ee0bffbc6/dbt-tests-adapter).

It sounds like you ran into a couple different things while upgrading [dbt-sqlserver](https://github.com/dbt-msft/dbt-sqlserver) to be compatible with dbt-core v1.8. But I'm not seeing anything that you're suggesting we change in the `dbt-adapters` specifically -- is that right?

If you have any feature requests or bugs related to the [cookiecutter template](https://github.com/dbt-labs/dbt-database-adapter-scaffold), could you please open up separate issue(s) here?
- https://github.com/dbt-labs/dbt-database-adapter-scaffold

If you have suggested updates to the [guide for building, testing, documenting, and promoting adapters](https://docs.getdbt.com/guides/adapter-creation?step=1), could you open separate issue(s) here?
- https://github.com/dbt-labs/docs.getdbt.com

That would help us get all the suggestions in the right places.

**Comment by cody-scott** [comment]
Correct. Not an issue, but rather more of clarification on the docs side. 

Example is should users clone from the git repo, or pypi. We opted for pypi pinning to the same 1.8 dbt version, and plan on doing the same for 1.9. 

Cookiecutter suggests repo, which is equally correct?

Seems sorted in our case but might be helpful for others in the future implementations. 

As an aside the new test framework has been great to work with vs the older one!

**Comment by dbeatty10** [comment]
> As an aside the new test framework has been great to work with vs the older one!

Awesome to hear! 🤩

> Example is should users clone from the git repo, or pypi. We opted for pypi pinning to the same 1.8 dbt version, and plan on doing the same for 1.9.
>
> Cookiecutter suggests repo, which is equally correct?

[This](https://github.com/dbt-msft/dbt-sqlserver/blob/ddf278f15d921c4ac9c883ae97cc68265a41f0fc/dev_requirements.txt#L2) is the approach you took, right?

```
dbt-tests-adapter>=1.8.0, <1.9.0
```

I can see how this would be useful to only run the tests that have been released in PyPI and align with the version range of `dbt-adapters` that you are targeting.

### Adapters maintained by dbt Labs

[This](https://github.com/dbt-labs/dbt-snowflake/blob/3fbc0749491f40d34014336457753b140e1fb1ee/dev-requirements.txt#L4) is how we do it for dbt-snowflake:

```python
git+https://github.com/dbt-labs/dbt-adapters.git#subdirectory=dbt-tests-adapter
```

When doing development, then we can [temporarily change](https://github.com/dbt-labs/dbt-snowflake/pull/1011/commits/7c4424dffd80e0dc93c3228bae13773903f58595) the specific branch that a change is being tested against as-needed:

```python
git+https://github.com/dbt-labs/dbt-adapters.git@BRANCH_NAME#subdirectory=dbt-tests-adapter
```

### Preparing an adapter for an upcoming release of dbt

We don't currently have any `1.8.latest` or `1.9.latest` branches within `dbt-adapters`, but if we did, then you could also do something like this:

```python
git+https://github.com/dbt-labs/dbt-adapters.git@1.8.latest#subdirectory=dbt-tests-adapter
```

This approach is especially useful if you are preparing your adapter to be ready for an upcoming release of `dbt-adapters` or `dbt-core` _before_ it is released.
