### ISSUE TITLE
[Bug] Unable to transfer issues from adapters in other github orgs to dbt-adapters

### ISSUE THREAD

**Issue by prdpsvs** [dbt-labs/dbt-adapters#287]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am unable to transfer an issue from dbt-fabric repository in microsoft github org to dbt-adapters repository in dbt-labs org. I believe, this is a permission issue and adapter maintainers should have access to transfer issues.

### Expected Behavior

I expect to move/transfer issues between dbt-fabric repository to dbt-adapters repository in differnt github accounts/orgs.

### Steps To Reproduce

1. Go to the dbt-fabric github repository.
2. Open any issue and click on transfer issue on bottom right.
3. I should see dbt-adapters repository as an option to transfer the issue.

### Environment

```markdown
- OS:
- Python:
- dbt-adapters:
```

**Comment by colin-rogers-dbt** [comment]
Note: [this is the original ticket](https://github.com/microsoft/dbt-fabric/issues/214)

**Comment by amychen1776** [comment]
@prdpsvs this isn't a bug but how Github works. You can't transfer issues from one org to another that you don't have the permissions to. I'm going to close this issue out for now because I don't see us changing the permissions for our org due to security concerns.
