### ISSUE TITLE
[Bug] dbt-core and dbt-adapters version mismatch

### ISSUE THREAD

**Issue by guenp** [dbt-labs/dbt-adapters#343]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After running `pip install dbt-core dbt-adapters dbt-duckdb`:

```
$ pip list | grep dbt
dbt-adapters              1.7.0
dbt-common                1.10.0
dbt-core                  1.8.8
dbt-duckdb                1.9.0
dbt-extractor             0.5.1
dbt-semantic-interfaces   0.5.1

$ dbt --version                                                                                                                   
Core:
  - installed: 1.8.8
  - latest:    1.8.8 - Up to date!

Plugins:
  - duckdb: 1.9.0 - Not compatible!
  ```

~`dbt-core` complains when the adapter version does not match the `dbt-core` version (see [line](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/version.py#L134)). Because we released `dbt-duckdb` 1.9.0 before `dbt-adapters` 1.9.0 got released that's an error that shows up.~ `dbt-adapters` 1.9.0 was just released! 🙌 

Another issue we're seeing is that `dbt-core` 1.8.8 depends on on `dbt-adapters` <1.7.1 (see [line](https://github.com/dbt-labs/dbt-core/blob/v1.8.8/core/setup.py#L79)) but the latest version is 1.8.0 (which just came out last week)
It seems like the solution to this would be for `dbt-core` to release a new version 1.9.0

### Expected Behavior

No errors or version conflicts and should install the latest versions:

```
$ pip list | grep dbt
dbt-adapters              1.9.0
dbt-common                1.12.0
dbt-core                  1.8.8
dbt-duckdb                1.9.0
dbt-extractor             0.5.1
dbt-semantic-interfaces   0.7.4

$ dbt --version
Core:
  - installed: 1.8.8
  - latest:    1.8.8 - Up to date!

Plugins:
  - duckdb: 1.9.0 - Up to date!
```

### Steps To Reproduce

Run `pip install dbt-core dbt-adapters dbt-duckdb` in a new Python environment and run

```
$ pip show | grep dbt
$ dbt --version
```

### Relevant log output

```shell
N/A
```

### Environment

```markdown
- OS:N/A
- Python:N/A
- dbt-adapters:1.8.8
```

### Additional Context

N/A

**Comment by joellabes** [comment]
This is a sibling of https://github.com/dbt-labs/dbt-core/issues/10230

**Comment by guenp** [comment]
Quick update: `dbt-adapters` 1.9.0 was just released!
As a workaround until `dbt-core` 1.9.0 is released we can just install `dbt-core` on the latest pre-release tag, i.e.

```
pip install dbt-core==1.9.0b4 dbt-adapters dbt-duckdb
```

This gives

```
$ pip list | grep dbt
dbt-adapters              1.9.0
dbt-common                1.12.0
dbt-core                  1.9.0b4
dbt-duckdb                1.9.0
dbt-extractor             0.5.1
dbt-semantic-interfaces   0.7.4

$ dbt --version
Core:
  - installed: 1.9.0-b4
  - latest:    1.8.8    - Ahead of latest version!

Plugins:
  - duckdb: 1.9.0 - Up to date!
```
