### ISSUE TITLE
Add github actions release workflow

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-adapters#4]
Need to add a workflow similar to what we have in other repos to handle bumping version and releasing
example: https://github.com/dbt-labs/dbt-bigquery/actions/workflows/release.yml

```[tasklist]
- [x] Release to PyPI
- [x] Release to PyPI Test
- [ ] Release to GitHub
- [ ] Release Docker
- [ ] Add version bumping
```

**Comment by mikealfare** [comment]
We still need to add version bumping
