### ISSUE TITLE
[Maintainership] GitHub Action to switch between the `awaiting_response` and `triage` labels

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-adapters#69]
### Housekeeping

- [X] I am a maintainer of dbt-adapters

### Short description

GitHub Action to switch between the `awaiting_response` and `triage` labels

### Acceptance criteria

- When a new issue is opened, it automatically has the `triage` label
- When an issue has the `awaiting_response` label and a user adds a comment, the `awaiting_response` label is removed and the `triage` label is added.

### Suggested Tests

N/A

### Impact to Other Teams

None.

### Will backports be required?

No.

**Comment by mikealfare** [comment]
I copied the existing workflow from `dbt-snowflake` and updated the name to be less prescriptive about the implementation. We use a single label today, but perhaps this changes in the future. And updating action names doesn't always work as intended.

As for the first bullet (When a new issue is opened, it automatically has the `triage` label), this occurs via the issue templates for bugs, regressions, and feature requests. It will not happen for internally submitted tickets, though I suspect this is what we want.

**Comment by mikealfare** [comment]
Oh, and I don't think `user docs` is correct, is it? That's the label we use to create a docs issue on docs.getdbt.com. Do we need something related to this in that repo?
